# need super user access
sudo: required 
# need services before commencing steps
services:
  - docker

# steps that run before tests or deployment is done
before_install:
  - docker build -t anmoldesai/hcard -f Dockerfile.dev .

# all commands to be executed. travis ci  watched the output
# if return code other than 0, then travis considers it failed
# default behaviour of yarn test is to run it and then put a watcher.
# travis ci expects test to end and exit successfully to be considered a pass.
script:
  - docker run -e CI=true anmoldesai/hcard yarn run test

deploy:
  provider: elasticbeanstalk # use these instructions to deploy. i,e ebs instructions
  region: "ap-southeast-2"
  app: "HCard"
  env: "Hcard-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-976196051615"
  bucket_path: "HCard" # this is the folder that is created in s3. All projects environment create a folder in this bucket 
  on:
    branch: master # only deploy when its master branch
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY